implementations:
  # Each benchmark can have its relevant configurations defined here.
  - name: WaiiBenchmark
    class: waii_benchmark.WaiiBenchmark
    description: Using Waii API for generating text-to-sql using openai GPT-4.
    threads_count: 3
    waii_configs:
      url: 'http://localhost:9859/api/'
      api_key: ''
      waii_db_connection_key: 'mysql://root@localhost:3308/northwind'
      waii_context: northwind_mariadb_context.json
      model: 'llama-v3p3'
      dialect: mysql
    databases:
      source:
        # Golden query runs in source DB
        type: sqlalchemy
        connection: 'mysql+mysqldb://root:root_password@127.0.0.1:3308/northwind'
      target:
        # Generated query runs in target DB
        # When target DB is same as source, we can use the same connection. Otherwise, provide type and connection string
        same_as_source: true

